codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 70..100
  round: down
  precision: 2

  status:
    project: yes
    patch: yes
    changes: no

  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
  javascript:
    enable_partials: yes

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no